### ISSUE TITLE
Running the provided script returns gpu_ids error

### ISSUE THREAD

**Issue by ravindra-ut** [pacman100/accelerate-megatron-test#1]
```
~/accelerate-megatron-test$ ./megatron_lm_gpt_pretraining.sh 
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/accelerate/commands/launch.py", line 747, in launch_command
    defaults = load_config_from_file(args.config_file)
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/accelerate/commands/config/config_args.py", line 64, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/accelerate/commands/config/config_args.py", line 117, in from_yaml_file
    return cls(**config_dict)
TypeError: __init__() got an unexpected keyword argument 'gpu_ids'
```
I removed the config and ran it on my ec2 machine, by enabling just cpu.

I still ended up with:
```
./megatron_lm_gpt_pretraining.sh 
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/accelerate/commands/launch.py", line 747, in launch_command
    defaults = load_config_from_file(args.config_file)
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/accelerate/commands/config/config_args.py", line 64, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/accelerate/commands/config/config_args.py", line 117, in from_yaml_file
    return cls(**config_dict)
TypeError: __init__() got an unexpected keyword argument 'megatron_lm_config'
```

**Comment by pacman100** [comment]
Hello @ravindra-ut , Megatron-LM features work with machines having at least 2 GPUs.

**Comment by pacman100** [comment]
So, when enabling just CPU, by design it shouldn't work, maybe I can have an early check to throw error with above message.

**Comment by ravindra-ut** [comment]
@pacman100 I tried on p3.8xlarge with 4 GPU's still ran into following error.

transformers==4.23.1
accelerate==0.12.0

```
(pytorch_p37) :~/accelerate-megatron-test$ ./megatron_lm_gpt_pretraining.sh 
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/accelerate/commands/launch.py", line 747, in launch_command
    defaults = load_config_from_file(args.config_file)
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/accelerate/commands/config/config_args.py", line 64, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/accelerate/commands/config/config_args.py", line 117, in from_yaml_file
    return cls(**config_dict)
TypeError: __init__() got an unexpected keyword argument 'megatron_lm_config'
```
<img width="1103" alt="Screen Shot 2022-10-21 at 1 33 44 PM" src="https://user-images.githubusercontent.com/22090962/197284709-6006e8b2-aacf-4f3d-b551-64ff109c510d.png">

**Comment by pacman100** [comment]
Hello, please use the main branch of the repo as MegatronLM integration is not yet part of the main release. It will be part of the next release. 

Please run below command:
```
pip install git+https://github.com/huggingface/accelerate.git
```

**Comment by ravindra-ut** [comment]
Yup, we can improve the readme or provide some requirements.txt(if you have).

- I installed accelerate from source. 0.14.0 dev.
- Upgraded pytorch 1.12.0.
- Installed Megatron from source.
ran into following error:
```
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/megatron/utils.py", line 23, in <modul
e>
    from apex.multi_tensor_apply import multi_tensor_applier
ModuleNotFoundError: No module named 'apex'
```
-  After pip3 install apex, ran into following error:
```
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/megatron/utils.py", line 23, in <module>
    from apex.multi_tensor_apply import multi_tensor_applier
  File "/home/ubuntu/anaconda3/envs/pytorch_p37/lib/python3.7/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
```

**Comment by ravindra-ut** [comment]
My mistake direct install of apex will not work. 

https://stackoverflow.com/questions/66610378/unencryptedcookiesessionfactoryconfig-error-when-importing-apex

I will post the solution, if I am able to get working here.

**Comment by pacman100** [comment]
I have put all the documentation of the pre-requisite https://huggingface.co/docs/accelerate/main/en/usage_guides/megatron_lm.

In Pre-requisites, step 3 clearly outlines how to install Apex as it can't be directly pip installed.
